[package]
name = "rusty-journal"
version = "0.1.0"
authors = ["陈新 <xin.chen3@domob.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"